### ISSUE TITLE
No Alt text on images no longer alerts user

### ISSUE THREAD

**Issue by gorriecoe** [silverstripe/cwp-core#55] opened 2018-11-06 03:54 UTC
In ss3 admin a user would get alerted if alt text wasn't defined.  This functionality isn't working with ss4.  Is this likely to be implemented?  I see the code is still in the repo but is using entwine which I assume no longer works with assets admin.

Alert message
```
{{ Image name }} has no alt text which is required for non-decorative images.

Are you sure you want to update?
```

**Comment by robbieaverill** [comment] 2018-11-06 09:31
You're probably right. I'll triage this as a high impact bug (due to missing functionality) and suggest that we add a Behat test to cover this functionality to prevent future regressions

**Comment by robbieaverill** [comment] 2019-03-08 03:21
Closing as a duplicate of https://github.com/silverstripe/cwp/issues/149

**Closed by robbieaverill** 2019-03-08 03:21 UTC
Labels: affects/v4, change/patch, effort/medium, impact/high, type/UX, type/bug
